version: '3.1'

services:
  mongo:
    image: mongo
    restart: always

  cms:
    image: keystone-image
    restart: always
    stdin_open: true
    command: "npm run dev"
    ports:
      - "8000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/keystone